dist: xenial
language: python
matrix:
    include:
        - python: 3.5
        - python: 3.6
        - python: 2.7
install:
  - if [["$TRAVIS_PYTHON_VERSION" == "2.7"]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh;
      bash Miniconda-latest-Linux-x86_64.sh -b;
      export PATH="$HOME/miniconda2/bin:$PATH";
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh;
      bash Miniconda3-latest-Linux-x86_64.sh -b;
      export PATH="$HOME/miniconda3/bin:$PATH";
    fi
  - conda env create -f environment.yml
  - source activate scikit-visualizations
  - conda install -y coverage nose pandas sphinx
  - pip install codeclimate-test-reporter coveralls recommonmark sphinxcontrib-napoleon travis-sphinx
script:
  - nosetests -x -v -d --with-coverage --cover-erase --cover-package=skvisualizations tests/*
  - coveralls
  - mkdir docs
  - export PYTHONPATH=`pwd`
  - sphinx-quickstart -q -p scikit-visualizations -a "David Diaz Vico" -v 0.1 -r 0.1.1 -l en --ext-autodoc --ext-viewcode --ext-githubpages --extensions sphinxcontrib.napoleon --no-makefile --no-batchfile docs
  - sphinx-apidoc -o docs/_static/ skvisualizations -F -a -l
  - travis-sphinx -v build -s docs -n
after_success:
  - codeclimate-test-reporter
  - travis-sphinx deploy